shell = "zsh"

[plugins]
[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-history-substring-search]
github = 'zsh-users/zsh-history-substring-search'

[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'

[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"