version: '3'
services:
  app:
  # mysql -h <container_name> -u <user> -D <db_name> -p
    container_name: 'django'
    build:
      context: ./src/django/
      dockerfile: Dockerfile
    working_dir: '/home/masakai/'
    image: masakai54/django
    networks:
      - app-net

  db:
    container_name: 'mysql-db'
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: masakai
      MYSQL_PASSWORD: masakai
    restart: 'always'
    expose:
      - '3306'
    ports:
      - "3306:3306"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge